[build]
  command = "npm run build"
  publish = ".next"
  functions = ".next/serverless"

[build.environment]
  NODE_VERSION = "20"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/_next/static/:path"
  to = "/_next/static/:path"
  status = 200
